
openapi: 3.0.0
info:
  title: Lightning Stats Dashboard API
  version: v1.0.0
  description: API for accessing Lightning Network node statistics and analytics data.
servers:
  - url: /api # Base path for API routes within the Next.js app
    description: Development server

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: A human-readable error message.
        details:
          type: string
          description: Optional additional details about the error.
          nullable: true
    
    # === Betweenness Schemas ===
    SingleCategoryTopNode:
      type: object
      properties:
        nodeid:
          type: string
          format: pubkey
          description: The public key of the Lightning node.
        alias:
          type: string
          nullable: true
          description: The alias of the node.
        categoryShare:
          type: number
          format: double
          nullable: true
          description: Shortest path share for the primary category this node is listed under.
        categoryRank:
          type: integer
          nullable: true
          description: Rank within the primary category.
        microShare:
          type: number
          format: double
          nullable: true
        microRank:
          type: integer
          nullable: true
        commonShare:
          type: number
          format: double
          nullable: true
        commonRank:
          type: integer
          nullable: true
        macroShare:
          type: number
          format: double
          nullable: true
        macroRank:
          type: integer
          nullable: true
      required:
        - nodeid

    AllTopNodes:
      type: object
      properties:
        micro:
          type: array
          items:
            $ref: '#/components/schemas/SingleCategoryTopNode'
        common:
          type: array
          items:
            $ref: '#/components/schemas/SingleCategoryTopNode'
        macro:
          type: array
          items:
            $ref: '#/components/schemas/SingleCategoryTopNode'
      required:
        - micro
        - common
        - macro

    NetworkSubsumptionDataPoint:
      type: object
      properties:
        date:
          type: string
          format: date
          description: The date for the data point.
        micro:
          type: number
          format: double
          description: Shortest path share percentage for micro payments.
        common:
          type: number
          format: double
          description: Shortest path share percentage for common payments.
        macro:
          type: number
          format: double
          description: Shortest path share percentage for macro payments.
      required:
        - date
        - micro
        - common
        - macro

    OurNodeCategoryRank:
      type: object
      properties:
        latestRank:
          type: integer
          nullable: true
        rankChange:
          type: integer
          nullable: true
          description: Change in rank compared to the start of the period (negative is better).
        latestShare:
          type: number
          format: double
          nullable: true
        previousShare:
          type: number
          format: double
          nullable: true
      required:
        - latestRank
        - rankChange
        - latestShare
        - previousShare
        
    OurNodeRanksForAllCategories:
      type: object
      properties:
        micro:
          $ref: '#/components/schemas/OurNodeCategoryRank'
        common:
          $ref: '#/components/schemas/OurNodeCategoryRank'
        macro:
          $ref: '#/components/schemas/OurNodeCategoryRank'
      required:
        - micro
        - common
        - macro

paths:
  /betweenness/top-nodes:
    get:
      summary: Get Top Nodes by Shortest Path Share
      description: Retrieves a list of top nodes ranked by their shortest path share for micro, common, and macro payment sizes.
      operationId: getTopNodesBySubsumption
      parameters:
        - name: limit
          in: query
          description: The number of top nodes to return for each category.
          required: false
          schema:
            type: integer
            default: 3
            minimum: 1
      responses:
        '200':
          description: Successfully retrieved top nodes data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllTopNodes'
        '400':
          description: Invalid parameter (e.g., limit).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /betweenness/node-timeline:
    get:
      summary: Get Node's Shortest Path Share Timeline
      description: Retrieves the historical shortest path share for a specific node across micro, common, and macro payment sizes, aggregated by a chosen period.
      operationId: getNetworkSubsumptionDataForNode
      parameters:
        - name: nodeId
          in: query
          description: The public key of the Lightning node to query.
          required: true
          schema:
            type: string
            format: pubkey
        - name: aggregation
          in: query
          description: The time period for aggregating data.
          required: false
          schema:
            type: string
            enum: [day, week, month, quarter]
            default: week
      responses:
        '200':
          description: Successfully retrieved node timeline data.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NetworkSubsumptionDataPoint'
        '400':
          description: Missing or invalid nodeId parameter.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  
  /betweenness/node-ranks:
    get:
      summary: Get Node's Ranks and Shares for All Categories
      description: Retrieves the latest rank, rank change, latest share, and previous share for a specific node across micro, common, and macro payment categories, based on the selected aggregation period.
      operationId: getNodeRanksForCategories
      parameters:
        - name: nodeId
          in: query
          description: The public key of the Lightning node.
          required: true
          schema:
            type: string
        - name: aggregation
          in: query
          description: Aggregation period (e.g., 'week', 'month').
          required: false
          schema:
            type: string
            default: 'week'
      responses:
        '200':
          description: Successfully retrieved node ranks and shares.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OurNodeRanksForAllCategories'
        '400':
          description: Invalid parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
