
'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import {
  Sidebar,
  SidebarHeader,
  SidebarContent,
  SidebarMenu,
  SidebarMenuItem,
  SidebarMenuButton,
  SidebarFooter,
} from '@/components/ui/sidebar';
import { Logo } from '@/components/logo';
import { LayoutDashboard, Users, BarChart3, GitCompareArrows, Github, BookText } from 'lucide-react';
import { Separator } from '@/components/ui/separator';
import { specificNodeId } from '@/lib/constants';

const navItems = [
  { href: '/', label: 'Overview', icon: LayoutDashboard },
  { href: '/channels', label: 'Channels', icon: Users },
  { href: '/analytics', label: 'Network Insights', icon: BarChart3 },
  { href: `/subsumption/${specificNodeId}`, label: 'Routing Analysis', icon: GitCompareArrows },
];

export function MainSidebar() {
  const pathname = usePathname();
  // Determine the base URL for MkDocs. If running locally (dev),
  // it might be on a different port. For production, it's served from the same domain.
  // Assuming MkDocs is served from the root of the same domain in production.
  // For local dev, `npm run docs:dev` typically serves on http://127.0.0.1:8000
  // This example assumes MkDocs is accessible from the same domain/port or a relative path.
  // If your MkDocs site is hosted at a different base URL, adjust `mkDocsBaseUrl` accordingly.
  const isDev = process.env.NODE_ENV === 'development';
  // For simplicity, we'll link to relative paths which MkDocs should handle.
  // If `docs` is served under a subpath like `/docs/` by Next.js itself (not typical for MkDocs separate build),
  // then paths would need to be prefixed. Assuming MkDocs output is at the root or a known relative path.

  const apiDocsPath = '/api-reference/'; // Path generated by MkDocs for api-reference.md

  return (
    <Sidebar collapsible="icon" className="border-r">
      <SidebarHeader className="p-4">
        <Logo size="md"/>
      </SidebarHeader>
      <SidebarContent className="p-2 flex-1">
        <SidebarMenu>
          {navItems.map((item) => (
            <SidebarMenuItem key={item.label}>
              <Link href={item.href}>
                <SidebarMenuButton
                  tooltip={item.label}
                  className="w-full justify-start"
                  isActive={item.href === `/subsumption/${specificNodeId}` ? pathname.startsWith('/subsumption') : (pathname === item.href || (item.href !== '/' && pathname.startsWith(item.href)))}
                >
                  <item.icon className="h-5 w-5" />
                  <span className="group-data-[collapsible=icon]/sidebar-wrapper:hidden">{item.label}</span>
                </SidebarMenuButton>
              </Link>
            </SidebarMenuItem>
          ))}
        </SidebarMenu>
      </SidebarContent>
      <Separator className="my-2" />
      <SidebarFooter className="p-2">
        <SidebarMenuItem>
           {/* 
            The link to API docs needs to go to the MkDocs generated site.
            If MkDocs is served from the same domain root: href="/api-reference/"
            If MkDocs is served under e.g. /docs: href="/docs/api-reference/"
            This assumes the MkDocs site is deployed such that `/api-reference/` is a valid path.
            If running `mkdocs serve`, it's usually at `http://127.0.0.1:8000/api-reference/`.
            For production, you'd configure your server to route to MkDocs content.
          */}
          <a href={apiDocsPath} target="_blank" rel="noopener noreferrer" className="w-full">
            <SidebarMenuButton
              tooltip="API Documentation"
              className="w-full justify-start"
              variant="ghost"
            >
              <BookText className="h-5 w-5" />
              <span className="group-data-[collapsible=icon]/sidebar-wrapper:hidden">API Docs</span>
            </SidebarMenuButton>
          </a>
        </SidebarMenuItem>
        <SidebarMenuItem>
          <a href="https://github.com/5satoshi/webapp" target="_blank" rel="noopener noreferrer" className="w-full">
            <SidebarMenuButton
              tooltip="Fork on GitHub"
              className="w-full justify-start"
              variant="ghost"
            >
              <Github className="h-5 w-5" />
              <span className="group-data-[collapsible=icon]/sidebar-wrapper:hidden">Fork on GitHub</span>
            </SidebarMenuButton>
          </a>
        </SidebarMenuItem>
      </SidebarFooter>
    </Sidebar>
  );
}
